### ISSUE TITLE
Compatibility with USGS web download format

### ISSUE THREAD

**Issue by jakeholden** [NREL/gradeit#6]
TIFF downloads of 1x1 degree tiles available from [The National Map from USGS](https://viewer.nationalmap.gov/basic/#productSearch). The "local" data source is currently configured to work with an older format raster database provided by USGS and used at NREL. Adding capability to use elevation data in the latest format will allow users to download individual tiles based on the location of the data that they wish to append elevation and grade to.

**Comment by nreinicke** [comment]
Included with the new loading using xarray in cc727b016522ecceb8b9bf30c806014bc8b7048e
